x-app-base: &app-base
  build:
    context: .
  ports:
    - target: 8080
      published: "${APP_PORT}"
  depends_on:
    migrations:
      condition: service_completed_successfully
  env_file:
    - .env
  volumes:
    - .:/app
    - /app/.venv


services:
  app:
    <<: *app-base
    build:
      args:
        UV_GROUPS: ""
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]


  app-debug:
    <<: *app-base
    build:
      args:
        UV_GROUPS: "--group debug"
    ports:
      #  Debug port
      - target: 5678
        published: "${DEBUG_PORT}"

    command: [
      "python",
      "-Xfrozen_modules=off",
      "-m",
      "debugpy",
      "--listen",
      "0.0.0.0:5678",
      "-m",
      "uvicorn",
      "app.main:app",
      "--host",
      "0.0.0.0",
      "--port",
      "8080",
      "--reload"
    ]


  migrations:
    <<: *app-base
    depends_on:
      postgres:
        condition: service_healthy

    command: ["alembic", "upgrade", "head"]


  postgres:
    image: postgres:16-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - target: 5432
        published: "${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: