"""fix expired_at column in AccessTokenModel

Revision ID: b854afcb3886
Revises: f8640513a824
Create Date: 2026-06-12 09:31:53.145762

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b854afcb3886"
down_revision: str | Sequence[str] | None = "f8640513a824"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("access_tokens", "expire_at", new_column_name="expired_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("access_tokens", "expired_at", new_column_name="expire_at")
    # ### end Alembic commands ###
