from app.shared.domain.errors import ApplicationError


class TokenExpiredError(ApplicationError): ...


class InvalidTokenError(ApplicationError): ...


class UserAlreadyExistsError(ApplicationError): ...


class InvalidCredentialsError(ApplicationError): ...
